services:
  db-postgres:
    container_name: db-arnuv
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: arnuv-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432
    volumes:
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

  arnuv-service:
    container_name: arnuv-service
    depends_on:
      - db-postgres
    image: arnuv-service:1.0.0
    environment:
      DB_HOST: db-arnuv
      DB_PORT: 5432
      DB_NAME: arnuv-db
      DB_USER: postgres
      DB_PASSWORD: postgres
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8087:8087